In [ ]:
import numpy as np
myPythonList = [1,9,8,3]
print(myPythonList) 

[1, 9, 8, 3]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[5,6,7]])
print(a.shape)

(2, 3)


In [ ]:
import numpy as np
a=np.array([[1,2,3],[5,6,7]])
b=np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
a=np.random.random((2,3))
print(a)

[[0.11121219 0.22988402 0.82162519]
 [0.96201764 0.9092232  0.50734865]]
